Feat/ux adjustments
kinhosz/Wallet-Platform pull request #20
Opened 2024-07-27 21:20 UTC by laysearaujo

- [ X ] Add: Profile image (need to update the backend)
- [ X ] Add: Route adjustments in login and signup
- [ X ] Add: Route configuration for authenticated user (after login, you cannot access login or signup)

2024-07-29 17:55 UTC, kinhosz requested changes
No geral tá muito legal, e a tela ficou muito boa também. Comentários gerais é só checar se tá responsivo. Na versão para celular você precisa scrollar pra baixo para ver o botão de `logout`.

2024-07-29 17:55 UTC, kinhosz commented on app/root.tsx
> +import { json, redirect, LoaderFunction } from '@remix-run/node';
onde tá usando o `json` ?

2024-07-29 17:55 UTC, kinhosz commented on app/root.tsx
> +// root.tsx
remove esse comentário

2024-07-29 17:55 UTC, kinhosz commented on app/routes/_layout.tsx
> +    window.location.href = '/logout';
a gente não vai criar uma rota de `/logout`, a gente pode só remover o cookie, pois sem o cookie, o front não vai conseguir fazer requisições. Uma forma de remover o cookie é setando sua data de expiração pro passado.

2024-07-29 17:55 UTC, kinhosz commented on app/routes/_layout.tsx
> +              alt="Profile"
tu tá usando o `context.user.profileImageUrl`, mas não vi onde tu setou esse dado. E por agora, não acho uma boa ideia a gente usar uma imagem mandada pelo usuário. Isso teria que mudar o backend para permitir avatares e criar uma rota específica pro usuário enviar a imagem. Por agora, eu prefiro deixar só um ícone padrão para todo mundo de perfil, e a gente adiciona foto no futuro.

2024-07-29 17:55 UTC, kinhosz commented on app/routes/_layout.tsx
> +      <main className={isSidebarOpen ? 'filter blur-sm' : ''}>
ótimo. mas vamos deixar as mensagens em inglês e tira os comentários

2024-07-29 17:55 UTC, kinhosz commented on app/routes/login.tsx
> +                    </div>
inglês + colocar essa opção embaixo do botão submit, o que acha?

2024-07-29 17:55 UTC, kinhosz commented on app/routes/signup.tsx
> +                    </div>
mesmo comentário anterior. inglês + essa mensagem embaixo do submit.

2024-07-29 17:55 UTC, kinhosz commented on app/types/context.ts
> +    profileImageUrl: string;
como sugeri, vamos evitar isso por enquanto.

2024-07-29 17:55 UTC, kinhosz commented
Comentário adicional: Linka esse PR com a issue do `logout` e adiciona um print screen na descrição do PR da tela codada.

2024-07-30 00:18 UTC, laysearaujo commented on app/root.tsx
> +import { json, redirect, LoaderFunction } from '@remix-run/node';
Não tá sendo usado, foi de um teste anterior. Removido na nova versão.

2024-07-30 00:22 UTC, laysearaujo commented on app/routes/_layout.tsx
> +    window.location.href = '/logout';
E vou encaminhar pra página de login

2024-07-30 01:23 UTC, laysearaujo commented on app/routes/login.tsx
> +                    </div>
Não gostei da mensagem embaixo, o que acha?
<img width="668" alt="Screenshot 2024-07-29 at 22 23 46" src="https://github.com/user-attachments/assets/736b4f3f-eb5d-4a4b-a9d3-b0442178e65e">

2024-07-30 01:33 UTC, laysearaujo commented
> No geral tá muito legal, e a tela ficou muito boa também. Comentários gerais é só checar se tá responsivo. Na versão para celular você precisa scrollar pra baixo para ver o botão de `logout`.

Fiz o teste em várias versões de aparelhos e nenhuma apresentou problemas de responsividade.

<img width="472" alt="Screenshot 2024-07-29 at 22 33 02" src="https://github.com/user-attachments/assets/5de0a5c0-27ba-47c0-bfae-ed377973abe1">

2024-07-30 09:28 UTC, kinhosz requested changes

2024-07-30 09:28 UTC, kinhosz commented on app/routes/_layout.tsx
> +  };
vamos evitar fazer as coisas na mão, o framework já tem um monte de coisas nesse tipo que pode ajudar e fica dinâmico. Por exemplo, para o `logout`, vamos fazer isso:

Cria uma rota `/logout` e dentro dela adiciona:
```ts
import { createCookie, LoaderFunction, redirect } from "@remix-run/node";

export const loader: LoaderFunction = async () => {
    const authCookie = createCookie('authToken');
    return redirect('/', {
        headers: {
        'Set-Cookie': await authCookie.serialize('', { expires: new Date(0) })
        }
    });
};

function Logout() {
    return null;
}

export default Logout;
```

dessa forma ele substitui o cookie, invalidando ele. E também é feito isso no lado do servidor remix, não no navegador do usuário.

2024-07-30 09:28 UTC, kinhosz commented on app/routes/_layout.tsx
> +          <div className="fixed inset-0 bg-black bg-opacity-50 backdrop-blur-sm z-40" onClick={toggleSidebar}></div>
se tem `onClick` então é `button` no lugar de `div`

2024-07-30 09:28 UTC, kinhosz commented on app/routes/_layout.tsx
> +            </div>
como a gente agora vai ter uma rota para `/logout` (perdão, na review anterior eu disse que a gente não ia ter a rota logout, mas eu fui testar e vi que era a melhor opção, my bad 🥹🤦‍♂️). Usa o `Link` (igual estamos usando dentro do componente `Tabsheet` para redirecionar para o `/logout`.

2024-07-30 09:28 UTC, kinhosz commented on app/routes/login.tsx
> +                                here
`<button>`

2024-07-30 09:28 UTC, kinhosz commented on app/routes/signup.tsx
> +                            </span>
`<button>`

2024-07-31 19:24 UTC, kinhosz approved these changes
LGTM. Ótimo trabalho em equipe. <3

2024-07-31 20:47 UTC, kinhosz requested changes

2024-07-31 20:47 UTC, kinhosz commented on app/routes/_layout.tsx
> +      <main className={isSidebarOpen ? 'filter blur-sm' : ''}>
eu sei que aprovei (perao). mas tava mexendo no layout agora... acho que fica legal se mover isso pra um componente, o que tu acha? pode fazer isso, svp?

2024-08-01 21:52 UTC, kinhosz approved these changes

2024-08-03 00:47 UTC, merged