feat: Add transactions
kinhosz/Wallet-Platform pull request #31
Opened 2024-09-19 00:21 UTC by laysearaujo

TODO:

- [ ] Fazer o editar
- [ ] Fazer o Add
- [ ] Configurar o back
- [ ] Carregar transações de acordo com a data selecionada

2024-11-04 10:20 UTC, kinhosz commented on app/components/transactions/dateNavigator.tsx
> +const DateNavigator = ({ currentDate, setCurrentDate }) => {
Adicionar especificação de tipo aqui

2024-11-04 17:00 UTC, kinhosz requested changes
Lazy review. Vamos revisar isso juntos. Aqui tá alguns problemas que encontrei, vamos tentar corrigir eles antes da revisão geral

### Issues

#### Quando a página recebe um refresh, um estranho erro é gerado

https://github.com/user-attachments/assets/cce2d809-5f4b-432b-ab46-c8cfd029acf8

#### Não consigo selecionar outra cor, fica travado na primeira selecionada

https://github.com/user-attachments/assets/806b147b-fef3-4641-b114-57d323fe2ee5

#### Não tá responsivo

https://github.com/user-attachments/assets/9a0a4041-9493-48c1-8675-4873028a1b57

#### O conteúdo da tela tá muito grande, precisamos montar um guia para deixar padronizado

#### Instala um linter de typescript ou coisa assim. Tem muito erro sendo gerado pq provavelmente tu não usa, e não aparece no teu pc

2024-11-05 19:46 UTC, kinhosz reviewed
Diminuir o tamanho da tela como um todo.
diminuir o tamanho do texto (tentar usar mesma UI do planning)
card ta transaction:
* menor espaco horizontal
* maior espaco vertical
* cor de fundo igual ao do planning

2024-11-21 22:05 UTC, laysearaujo commented
Fechando esse PR e criando outra branch como acordado.

2024-11-21 22:05 UTC, closed without merging