Feat/login page
kinhosz/Wallet-Platform pull request #8
Opened 2024-06-17 10:57 UTC by laysearaujo

#3

2024-06-17 11:27 UTC, kinhosz requested changes
Como um adicional, falta a gente ver como vai fazer no login, pois precisamos salvar o `token` que vem no `header` da requisicao. Pois, nas futuras chamadas de API, precisamos ter ele.

2024-06-17 11:27 UTC, kinhosz commented on app/routes/login.tsx
> +                </form>
usa o `Form`, que ai voce consegue usar o `useActionData` tambem

2024-06-17 11:27 UTC, kinhosz commented on app/routes/login.tsx
> +        }
mover isso pra `action`

2024-06-17 11:27 UTC, kinhosz commented on app/routes/login.tsx
> +                window.location.href = '/';
usa o `redirect`

2024-06-17 11:27 UTC, kinhosz commented on app/routes/login.tsx
> +            }
usa o `return json({})`

2024-06-17 11:27 UTC, kinhosz commented on app/routes/login.tsx
> +            setError('Failed to login. Please try again later.');
usa o `redirect` para o `internal error`

2024-06-17 11:28 UTC, kinhosz commented
Comentario adicional: tenta dar um `squash` e usa o `rebase` no lugar de `merge`

2024-06-27 17:47 UTC, kinhosz requested changes

2024-06-27 17:47 UTC, kinhosz commented on app/routes/login.tsx
> +        return json({ error: 'Failed to login. Please try again later.' }, { status: 500 });
```ts
return redirect('/error')
```

2024-06-27 17:47 UTC, kinhosz commented on app/routes/login.tsx
> +        }
```ts
} else {
    const data = await response.json();
    const errorMessage = data.status ? data.status.message : 'Unknown error';
    return json({ error: errorMessage });
}
```

A api já retorna a mensagem para esses erros, então a gente precisa só retornar ela.

2024-06-28 15:55 UTC, kinhosz requested changes

2024-06-28 15:55 UTC, kinhosz commented on app/routes/login.tsx
> +            // const errorMessage = data.status ? data.status.message : 'error';
so remove isso e mergea

2024-06-28 16:18 UTC, laysearaujo commented on app/routes/login.tsx
> +            // const errorMessage = data.status ? data.status.message : 'error';
falta teu aprove

2024-06-28 19:55 UTC, kinhosz approved these changes

2024-06-28 19:55 UTC, merged